language: elixir
elixir:
  - 1.3.2
env:
  - MIX_ENV=test
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/travis_ci_test.exs config/test.exs
  - mix do ecto.create, ecto.migrate
